swagger: "2.0"
info:
  description: "平台中心端服务"
  version: "1.0.0"
  title: "Apollo Center Service"
host: "10.10.3.12:4877"
basePath: "/api"
tags:
- name: "AssetCenter"
  description: "资源中心服务"
- name: "Asset"
  description: "资源服务"
- name: "Platform"
  description: "平台信息服务"
schemes:
- "https"
- "http"

paths:
  /platform/releases:
    get:
      tags:
        - "Platform"
      summary: "获取平台版本列表"
      produces:
      - "application/json"
      responses:
        "200":
          description: "注册资源包信息"
  /platform/release/{version}:
    get:
      tags:
        - "Platform"
      summary: "获取平台版本列表"
      produces:
      - "application/json"
      parameters:
      - name: "version"
        in: "path"
        description: "版本号，latest表示最新版本"
        default: "latest"
        required: true
        type: "string"
      responses:
        "200":
          description: "注册资源包信息"        
  /repo/register:
    post:
      tags:
      - "AssetCenter"
      summary: "注册中心端资源包"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "query"
        description: "资源包名称"
        required: true
        type: "string"
        default: "@gw/wind-pels-standard"
      - name: "type"
        in: "query"
        description: "资源包类型"
        required: true
        type: "string"
        default: "standard"
      responses:
        "200":
          description: "注册资源包信息"
  /repo/list:
    get:
      tags:
      - "AssetCenter"
      summary: "获取中心端资源包列表"
      description: ""
      produces:
      - "application/json"
      responses:
        "200":
          description: "资源包信息"
          schema: 
            $ref: '#/definitions/ResourceList'
  /repo/list/{type}:
    get:
      tags:
        - "AssetCenter"
      summary: "获取指定类型下的资源包列表"
      produces:
      - "application/json"
      parameters:
      - name: "type"
        in: "path"
        description: "资源包类型"
        default: "standard"
        required: true
        type: "string"
      responses:
        "200":
          description: "所有资源包列表信息"
  /repo/list/{type}/{tag}:
    get:
      tags:
        - "AssetCenter"
      summary: "获取指定类型和标签下的资源包列表"
      produces:
      - "application/json"
      parameters:
      - name: "type"
        in: "path"
        description: "资源包名称"
        default: "standard"
        required: true
        type: "string"
      - name: "tag"
        in: "path"
        description: "资源包标签"
        default: "latest"
        required: true
        type: "string"
      responses:
        "200":
          description: "所有资源包列表信息"
  /repo/versions:
    get:
      tags:
        - "AssetCenter"
      summary: "获取指定类型和标签下的资源包列表"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "query"
        description: "资源包名称"
        default: "standard"
        required: true
        type: "string"
      responses:
        "200":
          description: "所有资源包列表信息"
  /repo/unregister:
    post:
      tags:
      - "AssetCenter"
      summary: "取消注册中心端资源包"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "query"
        description: "资源包名称"
        required: true
        type: "string"
        default: "@gw/wind-pels-standard"
      responses:
        "200":
          description: "取消资源包信息"
  /assets/install:
    get:
      tags:
      - "Asset"
      summary: "安装/更新资源包"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "query"
        description: "资源包名称"
        required: true
        type: "string"
        default: "@gw/wind-pels-standard"
      - name: "app"
        in: "query"
        description: "所属应用"
        required: true
        type: "string"
        default: "icms"
      - name: "version"
        in: "query"
        description: "资源包版本名称（默认采用latest的版本）"
        required: true
        type: "string"
      responses:
        "200":
          description: "组织机构下拥有的资源包"
          schema: 
            $ref: '#/definitions/ResourceList'
  /assets/pkg/info:
    get:
      tags:
      - "Asset"
      summary: "获取资源包信息"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "query"
        description: "资源包名称"
        required: true
        type: "string"
        default: "@gw/wind-pels-standard"
      - name: "app"
        in: "query"
        description: "所属应用"
        required: true
        type: "string"
        default: "icms"
      - name: "version"
        in: "query"
        description: "资源包版本"
        type: "string"
        default: "1.0.4"
      responses:
        "200":
          description: "资源包信息"
          schema: 
            $ref: '#/definitions/ResourceList'
  /assets/{name}:
    delete:
      tags:
        - "Asset"
      summary: "删除资源包"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "path"
        description: "资源包名称"
        default: "@gw/wind-pels-standard"
        required: true
        type: "string"
      - name: "app"
        in: "query"
        description: "所属应用"
        required: true
        type: "string"
        default: "icms"
      responses:
        "200":
          description: "所有资源包版本信息"
          schema: 
            $ref: '#/definitions/ResourceList'
definitions:
  ResourceList:
    type: "object"
    properties:
      code:
        type: "integer"
        description: "状态码"
        format: "int64"
      msg:
        type: "string"
        description: "类型"
      data:
        type: "array"
        items: 
          type: "string"
          description: "资源名称"