export default {
    v: "7.0.7",
    p: { autoAdjustIndex: true, hierarchicalRendering: true },
    a: {
      rotateAsClock: false,
      connectActionType: null,
      name: "展示页面",
      width: 5120,
      height: 1080,
      background: "#fff",
      gridable: true,
      gridSplitX: 48,
      gridSplitY: 36,
      fileList: [],
      _id: "X1q1jz40cgd66Z1c",
      opacity: 1,
    },
    modified: "Thu Jan 14 2021 14:40:41 GMT+0800 (中国标准时间)",
    contentRect: { x: 0, y: 0, width: 5120, height: 1080 },
    d: [
      {
        c: "ht.Node",
        i: 47,
        p: {
          image: "HTMLSymbol",
          position: { x: 332.81903, y: 132.49126 },
          width: 450.47073,
          height: 84.65757,
        },
        s: { shape: null },
        a: {
          pel: {
            packageName: "@gw/soam-standard-status",
            version: "0.2.31",
            name: "build/soam_alarmList-status.fcp.js",
            path: "build/soam_alarmList-status.fcp.js",
            title: "告警列表",
            icon: "DeliveredProcedureOutlined",
          },
          guid: "P5hDgk",
          propsData: { width: 450.47073, height: 84.65757 },
        },
      },
      {
        c: "ht.Node",
        i: 48,
        p: {
          image: "HTMLSymbol",
          position: { x: 220.20135, y: 224.39868 },
          width: 225.23536,
          height: 99.15728,
        },
        s: { shape: null },
        a: {
          pel: {
            packageName: "@gw/soam-standard-status",
            version: "0.2.31",
            name: "build/soam_status1-status.fcp.js",
            path: "build/soam_status1-status.fcp.js",
            title: "soam_指标1",
            icon: "MenuOutlined",
          },
          guid: "t9ie2b",
          propsData: { width: 225.23536, height: 99.15728 },
        },
      },
      {
        c: "ht.Node",
        i: 50,
        p: {
          image: "HTMLSymbol",
          position: { x: 264.94545, y: 500.68431 },
          width: 150,
          height: 50,
        },
        s: { shape: null },
        a: {
          pel: {
            packageName: "@gw/soam-standard-status",
            version: "0.2.31",
            name: "build/soam_status3-status.fcp.js",
            path: "build/soam_status3-status.fcp.js",
            title: "soam_指标3",
            icon: "EllipsisOutlined",
          },
          guid: "yCIb8t",
          propsData: { width: 150, height: 50 },
        },
      },
      {
        c: "ht.Node",
        i: 51,
        p: {
          image: "HTMLSymbol",
          position: { x: 996.80941, y: 212.56741 },
          width: 395.29817,
          height: 325.42502,
        },
        s: { shape: null },
        a: {
          pel: {
            packageName: "@gw/standard-pels",
            version: "0.2.18",
            name: "build/chart_singleArea-status.fcp.js",
            path: "build/chart_singleArea-status.fcp.js",
            title: "无坐标面积图",
            icon: "AreaChartOutlined",
          },
          guid: "Rs6m21",
          propsData: { width: 395.29817, height: 325.42502 },
        },
      },
      {
        c: "ht.Node",
        i: 52,
        p: {
          image: "HTMLSymbol",
          position: { x: 639.24649, y: 899.30357 },
          width: 675.45762,
          height: 284.47411,
        },
        s: { shape: null },
        a: {
          pel: {
            packageName: "@gw/standard-pels",
            version: "0.2.18",
            name: "build/chart_switchColumn-status.fcp.js",
            path: "build/chart_switchColumn-status.fcp.js",
            title: "可切换柱状图",
            icon: "BarChartOutlined",
          },
          guid: "dKwPN3",
          propsData: { width: 675.45762, height: 284.47411 },
        },
      },
      {
        c: "ht.Node",
        i: 53,
        p: {
          image: "HTMLSymbol",
          position: { x: 1230.08537, y: 1020.37623 },
          width: 170.69018,
          height: 42.32878,
        },
        s: { shape: null },
        a: {
          pel: {
            packageName: "@gw/standard-pels",
            version: "0.2.18",
            name: "build/select-status.fcp.js",
            path: "build/select-status.fcp.js",
            title: "下拉框",
            icon: "DatabaseOutlined",
          },
          guid: "V7FlOF",
          propsData: { width: 170.69018, height: 42.32878 },
        },
      },
      {
        c: "ht.Node",
        i: 54,
        p: {
          image: "HTMLSymbol",
          position: { x: 558.05439, y: 601.62357 },
          width: 513.07344,
          height: 310.88589,
        },
        s: { shape: null },
        a: {
          pel: {
            packageName: "@gw/standard-pels",
            version: "0.2.18",
            name: "build/strand_shadedPolyline-status.fcp.js",
            path: "build/strand_shadedPolyline-status.fcp.js",
            title: "标准阴影折线图",
            icon: "BarChartOutlined",
          },
          guid: "weIHJj",
          propsData: { width: 513.07344, height: 310.88589 },
        },
      },
      {
        c: "ht.Node",
        i: 56,
        p: {
          image: "HTMLSymbol",
          position: { x: 536.76699, y: 247.79675 },
          anchor: { x: 0.5, y: 0.58876 },
          width: 343.50498,
          height: 301.54959,
        },
        s: { shape: null },
        a: {
          pel: {
            packageName: "@gw/standard-pels",
            version: "0.2.18",
            name: "build/strand_triangleList-status.fcp.js",
            path: "build/strand_triangleList-status.fcp.js",
            title: "带三角的列表",
            icon: "Loading3QuartersOutlined",
          },
          guid: "kSB1Xx",
          propsData: { width: 343.50498, height: 301.54959 },
        },
      },
      {
        c: "ht.Node",
        i: 58,
        p: {
          image: "HTMLSymbol",
          position: { x: -408.91979, y: -74.34905 },
          width: 200,
          height: 90,
        },
        s: { shape: null },
        a: {
          pel: {
            packageName: "@gw/standard-pels",
            version: "0.2.18",
            name: "build/chart_annotation-status.fcp.js",
            path: "build/chart_annotation-status.fcp.js",
            title: "仪表盘",
            icon: "DotChartOutlined",
          },
          guid: "FF6gaC",
          propsData: { width: 200, height: 90 },
        },
      },
      {
        c: "ht.Node",
        i: 88,
        p: {
          image: "HTMLSymbol",
          position: { x: 1831.48434, y: 221.03245 },
          width: 441.27042,
          height: 342.35509,
        },
        s: { shape: null },
        a: {
          pel: {
            packageName: "@gw/standard-pels",
            version: "0.2.20",
            name: "build/chart_areaLineWithBg-status.fcp.js",
            path: "build/chart_areaLineWithBg-status.fcp.js",
            title: "面积折线图",
            icon: "AreaChartOutlined",
          },
          guid: "FZwh6L",
          propsData: { width: 441.27042, height: 342.35509 },
        },
      },
      {
        c: "ht.Node",
        i: 89,
        p: {
          image: "HTMLSymbol",
          position: { x: 1402.65381, y: 224.39868 },
          width: 345.13688,
          height: 349.08756,
        },
        s: { shape: null },
        a: {
          pel: {
            packageName: "@gw/standard-pels",
            version: "0.2.20",
            name: "build/chart_area-status.fcp.js",
            path: "build/chart_area-status.fcp.js",
            title: "面积图",
            icon: "AreaChartOutlined",
          },
          guid: "DaF8Qz",
          propsData: { width: 345.13688, height: 349.08756 },
        },
      },
      {
        c: "ht.Node",
        i: 90,
        p: {
          image: "HTMLSymbol",
          position: { x: 2172.57772, y: 119.98892 },
          width: 169.66259,
          height: 140.26803,
        },
        s: { shape: null },
        a: {
          pel: {
            packageName: "@gw/standard-pels",
            version: "0.2.20",
            name: "build/chart_annotation-status.fcp.js",
            path: "build/chart_annotation-status.fcp.js",
            title: "仪表盘",
            icon: "DotChartOutlined",
          },
          guid: "g4DkxF",
          propsData: { width: 169.66259, height: 140.26803 },
        },
      },
      {
        c: "ht.Node",
        i: 119,
        p: {
          image: "HTMLSymbol",
          position: { x: 958.09753, y: 515.34208 },
          width: 172.55332,
          height: 172.56298,
        },
        s: { shape: null },
        a: {
          pel: {
            packageName: "@gw/standard-pels",
            version: "0.2.20",
            name: "build/circle_progressBar-status.fcp.js",
            path: "build/circle_progressBar-status.fcp.js",
            title: "圆形进度条",
            icon: "Loading3QuartersOutlined",
          },
          guid: "XXoNOE",
          propsData: { width: 172.55332, height: 172.56298 },
        },
      },
      {
        c: "ht.Node",
        i: 120,
        p: {
          image: "HTMLSymbol",
          position: { x: 1162.58537, y: 500.68431 },
          width: 135,
          height: 135,
        },
        s: { shape: null },
        a: {
          pel: {
            packageName: "@gw/standard-pels",
            version: "0.2.20",
            name: "build/progress_bar12-status.fcp.js",
            path: "build/progress_bar12-status.fcp.js",
            title: "进度条12",
            icon: "Loading3QuartersOutlined",
          },
          guid: "UFww5I",
          propsData: { width: 135, height: 135 },
        },
      },
      {
        c: "ht.Node",
        i: 121,
        p: {
          image: "HTMLSymbol",
          position: { x: 2383.18304, y: 273.97732 },
          width: 590.87322,
          height: 75.34223,
        },
        s: { shape: null },
        a: {
          pel: {
            packageName: "@gw/standard-pels",
            version: "0.2.20",
            name: "build/progress_bar2-status.fcp.js",
            path: "build/progress_bar2-status.fcp.js",
            title: "进度条2",
            icon: "DashOutlined ",
          },
          guid: "FXJXdf",
          propsData: { width: 590.87322, height: 75.34223 },
        },
      },
      {
        c: "ht.Node",
        i: 152,
        p: {
          image: "HTMLSymbol",
          position: { x: 1528.27605, y: 661.87334 },
          width: 509.65097,
          height: 431.38544,
        },
        s: { shape: null },
        a: {
          pel: {
            packageName: "@gw/standard-pels",
            version: "0.2.20",
            name: "build/strand_map-status.fcp.js",
            path: "build/strand_map-status.fcp.js",
            title: "标准地图",
            icon: "SlackOutlined",
          },
          guid: "jgjkqQ",
          propsData: { width: 509.65097, height: 431.38544 },
        },
      },
    ],
  }
