export default {
  v: "7.0.7",
  p: {
    background: "black",
    autoAdjustIndex: true,
    hierarchicalRendering: true,
  },
  a: {
    rotateAsClock: false,
    connectActionType: null,
    name: "展示页面",
    width: 1920,
    height: 1080,
    background: "black",
    gridable: true,
    gridSplitX: 48,
    gridSplitY: 36,
    fileList: [],
    _id: "jr5U1nh77AEz3ycJ",
  },
  modified: "Tue Jun 01 2021 15:55:55 GMT+0800 (中国标准时间)",
  contentRect: { x: 0, y: 0, width: 1920, height: 1080 },
  d: [
    {
      c: "ht.Node",
      i: 61,
      p: {
        image: "HTMLSymbol",
        position: { x: -61.974, y: 50.01523 },
        anchor: { x: -0.20658, y: 0.25 },
        width: 300,
        height: 200,
      },
      s: { shape: null },
      a: {
        "pel-events": [],
        pel: {
          packageName: "@gw/apollo-standard-containers",
          version: "1.0.13",
          name: "build/control-container-index.fcp.js",
          path: "build/control-container-index.fcp.js",
          title: "方法测试",
          icon: "BorderHorizontalOutlined",
        },
        guid: "q7lQfT",
        propsData: { width: 300, height: 200, linkRefs: ["UKS6d5", "grACdu"] },
        expressionBind: { p: {}, a: {}, s: {} },
        outside: true,
      },
    },
    {
      c: "ht.Node",
      i: 92,
      p: {
        name: "标题1",
        image: "HTMLSymbol",
        position: { x: 921.0358, y: 100.01523 },
        width: 120,
        height: 40,
      },
      s: { shape: null },
      a: {
        pel: {
          packageName: "@gw/apollo-standard-basic",
          version: "1.0.2",
          name: "build/title-status.fcp.js",
          path: "build/title-status.fcp.js",
          title: "标题",
          icon: "previews/title.svg",
          previewUrl:
            "/api/icms/unpkg/@gw/apollo-standard-basic@1.0.2/previews/title.svg",
        },
        guid: "UKS6d5",
        propsData: { width: 120, height: 40 },
        expressionBind: { p: {}, a: {}, s: {} },
        outside: true,
      },
    },
    {
      c: "ht.Node",
      i: 93,
      p: {
        name: "标题2",
        image: "HTMLSymbol",
        position: { x: 921.0358, y: 180 },
        width: 120,
        height: 40,
      },
      s: { shape: null },
      a: {
        pel: {
          packageName: "@gw/apollo-standard-basic",
          version: "1.0.2",
          name: "build/title-status.fcp.js",
          path: "build/title-status.fcp.js",
          title: "标题",
          icon: "previews/title.svg",
          previewUrl:
            "/api/icms/unpkg/@gw/apollo-standard-basic@1.0.2/previews/title.svg",
        },
        guid: "grACdu",
        propsData: { width: 120, height: 40 },
        expressionBind: { p: {}, a: {}, s: {} },
        outside: true,
      },
    },
  ],
};
