export default {
  v: "7.0.1-dev24",
  p: { autoAdjustIndex: true, hierarchicalRendering: true },
  a: {
    rotateAsClock: false,
    connectActionType: null,
    pageId: "4jp0WtYkw2pZAhEM",
    name: "展示页面",
    width: 1920,
    height: 1080,
    background: "#fff",
    gridable: true,
    gridSplitX: 48,
    gridSplitY: 36,
    fileList: [],
    zoom: 0.70103,
    _id: "4jp0WtYkw2pZAhEM",
  },
  d: [
    {
      c: "ht.Node",
      i: 50,
      p: {
        image: "HTMLSymbol",
        position: { x: 200, y: 100 },
        width: 304.4953,
        height: 133.42164,
      },
      s: { shape: null },
      a: {
        pel: {
          packageName: "@gw/soam-standard-status",
          version: "0.2.4",
          name: "./build/1-status.fcp.js",
          path: "./build/1-status.fcp.js",
          title: "soam_指标1",
        },
        guid: "7zM7MO",
        propsData: {
          titleFontSize: 24,
          valueFontSize: 48,
          unitFontSize: 16,
          titleColor: "#83b3ff",
          valueColor: "#ffffff",
          unitColor: "rgba(255, 255, 255, 0.5)",
          statistics: { label: "累计发电量", unit: "(万kWh)", value: "--" },
          _node: {
            x: 91.73897,
            y: 160.32117,
            width: 304.4953,
            height: 133.42164,
            movable: true,
            resizable: true,
            visible: true,
          },
          width: 304.4953,
          height: 133.42164,
        },
      },
    }
  ],
  modified: "Fri Aug 28 2020 13:47:05 GMT+0800 (中国标准时间)",
  contentRect: { x: 0, y: 0, width: 800, height: 600 },
};
